package com.qishon.test;

public enum InterfaceName {
    GETTOKEN,GS_SYS_SHOPLOGIN,GS_SYS_AMDPWD,MAT_MDL_GETNAVCLASSLIST,GS_SYS_GETPERSONINFOBYJOB,GS_SYS_REGDEVICEINF,
    GS_PROD_LIST,GS_PROD_GETPRODINFO,GS_PROD_GETPRODORDDETAIL,GS_MATCH_GETFITPRODINFONEW,GS_MATCH_GET3DMODELINFONEW,
    GS_MATCH_GETFITPRODRENDERNEW,GS_PROD_GETREGIONBYTYPE,GS_PROD_GETREPLACEPART,GS_MAS_FILTERPRODFABRICATTR,
    GS_PROD_DETAIL,GS_PROD_GETPRODREGIONBYPRINT,GS_PROD_GETPRINTBYREGION,GS_MAS_GETEMBCUSTOMLIST,GS_CUS_SAVECUSTOM,
    GS_CUS_GETCUSTOMLIST
}
